/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zou_autotouch_jni_InputEventJni */

#ifndef _Included_com_zou_autotouch_jni_InputEventJni
#define _Included_com_zou_autotouch_jni_InputEventJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zou_autotouch_jni_InputEventJni
 * Method:    touchdown
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_zou_autotouch_jni_InputEventJni_touchdown
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zou_autotouch_jni_InputEventJni
 * Method:    touchmove
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_zou_autotouch_jni_InputEventJni_touchmove
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zou_autotouch_jni_InputEventJni
 * Method:    touchup
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_zou_autotouch_jni_InputEventJni_touchup
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zou_autotouch_jni_InputEventJni
 * Method:    touch
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_zou_autotouch_jni_InputEventJni_touch
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
